name: Append Test Cases & Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Append Test Cases to main.c
      run: |
        # Backup original main.c
        cp main.c original_main.c
        
        # Add function prototype
        echo '' >> main.c
        echo 'void runTestCases();' >> main.c
        echo '' >> main.c

        # Insert test case function
        echo 'void runTestCases() {' >> main.c
        echo '    int arr1[] = {2, 1, 4, 7, 3, 2, 5};' >> main.c
        echo '    printf("Test 1: Expected 5, Got %d\\n", longestMountain(arr1, 7));' >> main.c
        echo '' >> main.c
        echo '    int arr2[] = {1, 3, 5, 3, 4, 2, 0, 8, 10, 7, 6, 5, 4, 3, 1};' >> main.c
        echo '    printf("Test 2: Expected 9, Got %d\\n", longestMountain(arr2, 15));' >> main.c
        echo '' >> main.c
        echo '    int arr3[] = {2, 1, 3, 2, 1, 5, 6, 5, 2, 1};' >> main.c
        echo '    printf("Test 3: Expected 6, Got %d\\n", longestMountain(arr3, 10));' >> main.c
        echo '' >> main.c
        echo '    int arr4[] = {2, 2, 2};' >> main.c
        echo '    printf("Test 4: Expected 0, Got %d\\n", longestMountain(arr4, 3));' >> main.c
        echo '' >> main.c
        echo '    int arr5[] = {0, 1, 0};' >> main.c
        echo '    printf("Test 5: Expected 3, Got %d\\n", longestMountain(arr5, 3));' >> main.c
        echo '}' >> main.c
        echo '' >> main.c

        # Modify main function to call runTestCases()
        sed -i 's/return 0;/    runTestCases();\n    return 0;/' main.c

    - name: Compile the Program
      run: gcc main.c -o main

    - name: Run the Program
      run: ./main
