name: Append Test Cases & Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Append Test Cases & main() to main.c
        run: |
          echo '' >> main.c
          echo 'void runTestCases() {' >> main.c
          echo '    int arr1[] = {2, 1, 4, 7, 3, 2, 5};' >> main.c
          echo '    int arr2[] = {2, 2, 2};' >> main.c
          echo '    int arr3[] = {0, 2, 0, 2, 1, 2, 3, 4, 5, 2, 1, 0};' >> main.c
          echo '    int arr4[] = {2, 3, 4, 5, 6, 7};' >> main.c
          echo '    int arr5[] = {1, 2, 3, 4, 3, 2, 1, 0};' >> main.c
          echo '    int expected[] = {5, 0, 5, 0, 8};' >> main.c
          echo '    int results[5];' >> main.c
          echo '    int passed = 0, failed = 0;' >> main.c
          echo '    results[0] = longestMountain(arr1, 7);' >> main.c
          echo '    results[1] = longestMountain(arr2, 3);' >> main.c
          echo '    results[2] = longestMountain(arr3, 12);' >> main.c
          echo '    results[3] = longestMountain(arr4, 6);' >> main.c
          echo '    results[4] = longestMountain(arr5, 8);' >> main.c
          echo '    for (int i = 0; i < 5; i++) {' >> main.c
          echo '        int success = (expected[i] == results[i]);' >> main.c
          echo '        printf("Test %d: Expected %d, Got %d --> %s\\n", i + 1, expected[i], results[i], success ? "✅ PASS" : "❌ FAIL");' >> main.c
          echo '        if (success) passed++; else failed++;' >> main.c
          echo '    }' >> main.c
          echo '    printf("\\nSummary: %d/%d tests passed, %d failed.\\n", passed, 5, failed);' >> main.c
          echo '}' >> main.c
          echo '' >> main.c
          echo 'int main() {' >> main.c
          echo '    runTestCases();' >> main.c
          echo '    return 0;' >> main.c
          echo '}' >> main.c

      - name: Compile the Program
        run: gcc main.c -o main

      - name: Run the Program
        run: ./main
