name: Append Test Cases & Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Append Test Cases & main() to main.c
        run: |
          echo '' >> main.c
          echo 'void runTestCases() {' >> main.c
          echo '    int arr1[] = {2, 1, 4, 7, 3, 2, 5};' >> main.c
          echo '    int arr2[] = {2, 2, 2};' >> main.c
          echo '    int arr3[] = {0, 2, 0, 2, 1, 2, 3, 4, 5, 2, 1, 0};' >> main.c
          echo '    int arr4[] = {2, 3, 4, 5, 6, 7};' >> main.c
          echo '    int arr5[] = {1, 2, 3, 4, 3, 2, 1, 0};' >> main.c
          echo '    printf("Test 1: Expected 5, Got %d\\n", longestMountain(arr1, 7));' >> main.c
          echo '    printf("Test 2: Expected 0, Got %d\\n", longestMountain(arr2, 3));' >> main.c
          echo '    printf("Test 3: Expected 5, Got %d\\n", longestMountain(arr3, 12));' >> main.c
          echo '    printf("Test 4: Expected 0, Got %d\\n", longestMountain(arr4, 6));' >> main.c
          echo '    printf("Test 5: Expected 8, Got %d\\n", longestMountain(arr5, 8));' >> main.c
          echo '}' >> main.c
          echo '' >> main.c
          echo 'int main() {' >> main.c
          echo '    runTestCases();' >> main.c
          echo '    return 0;' >> main.c
          echo '}' >> main.c

      - name: Compile the Program
        run: gcc main.c -o main

      - name: Run the Program
        run: ./main
