name: Append Testcases & Run C Program

on:
  push:
    paths:
      - "main.c"
  workflow_dispatch:

jobs:
  append-testcase-build-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Append Test Cases to main.c
        run: |
          echo 'int main() {' > temp_main.c
          cat main.c >> temp_main.c
          echo 'printf("Test Case: 2 + 2 = %d\n", 2+2);' >> temp_main.c
          echo 'return 0;' >> temp_main.c
          echo '}' >> temp_main.c
          mv temp_main.c main.c
          cat main.c  # Debug: Show final main.c

      - name: Compile the Program
        run: |
          gcc main.c -o main
          ls -l  # Debug: Verify if the executable exists

      - name: Run and Test
        run: |
          chmod +x main  # Ensure executable permissions
          ./main
